{% set version = "1.0.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-varnish
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/carpentries/varnish/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6d9a38d1219db45160e5e13ea42dcb9cd5c2b7fb5c5f1bcf48feb53e930c8022

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('varnish')"           # [not win]
    - "\"%R%\" -e \"library('varnish')\""  # [win]

about:
  home: https://github.com/carpentries/varnish
  license: MIT
  summary: The Carpentries Lesson HTML Templates
  description: |
    This project does not contain any useful R code.
    It contains HTML templates with mustache syntax, CSS, and JavaScript.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - matthewfeickert
